/*
 * This file is generated by jOOQ.
 */
package com.treetory.test.mvc.model.test.tables.records;


import com.treetory.test.mvc.model.test.tables.RawlogTest;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RawlogTestRecord extends UpdatableRecordImpl<RawlogTestRecord> implements Record3<Integer, String, Timestamp> {

    private static final long serialVersionUID = -1110567050;

    /**
     * Setter for <code>test.RAWLOG_TEST.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.RAWLOG_TEST.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.RAWLOG_TEST.log</code>.
     */
    public void setLog(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.RAWLOG_TEST.log</code>.
     */
    public String getLog() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.RAWLOG_TEST.system_timestamp</code>.
     */
    public void setSystemTimestamp(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.RAWLOG_TEST.system_timestamp</code>.
     */
    public Timestamp getSystemTimestamp() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RawlogTest.RAWLOG_TEST.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RawlogTest.RAWLOG_TEST.LOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return RawlogTest.RAWLOG_TEST.SYSTEM_TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLog();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getSystemTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLog();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getSystemTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RawlogTestRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RawlogTestRecord value2(String value) {
        setLog(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RawlogTestRecord value3(Timestamp value) {
        setSystemTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RawlogTestRecord values(Integer value1, String value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RawlogTestRecord
     */
    public RawlogTestRecord() {
        super(RawlogTest.RAWLOG_TEST);
    }

    /**
     * Create a detached, initialised RawlogTestRecord
     */
    public RawlogTestRecord(Integer id, String log, Timestamp systemTimestamp) {
        super(RawlogTest.RAWLOG_TEST);

        set(0, id);
        set(1, log);
        set(2, systemTimestamp);
    }
}
