/*
 * This file is generated by jOOQ.
 */
package com.treetory.test.mvc.model.test;


import com.treetory.test.mvc.model.test.tables.RawlogTest;
import com.treetory.test.mvc.model.test.tables.records.RawlogTestRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RawlogTestRecord, Integer> IDENTITY_RAWLOG_TEST = Identities0.IDENTITY_RAWLOG_TEST;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RawlogTestRecord> KEY_RAWLOG_TEST_PRIMARY = UniqueKeys0.KEY_RAWLOG_TEST_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<RawlogTestRecord, Integer> IDENTITY_RAWLOG_TEST = Internal.createIdentity(RawlogTest.RAWLOG_TEST, RawlogTest.RAWLOG_TEST.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<RawlogTestRecord> KEY_RAWLOG_TEST_PRIMARY = Internal.createUniqueKey(RawlogTest.RAWLOG_TEST, "KEY_RAWLOG_TEST_PRIMARY", RawlogTest.RAWLOG_TEST.ID);
    }
}
