/*
 * This file is generated by jOOQ.
 */
package com.treetory.test.mvc.model.test;


import com.treetory.test.mvc.model.test.tables.NormalizedlogTest;
import com.treetory.test.mvc.model.test.tables.RawlogTest;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.NORMALIZEDLOG_TEST</code>.
     */
    public static final NormalizedlogTest NORMALIZEDLOG_TEST = com.treetory.test.mvc.model.test.tables.NormalizedlogTest.NORMALIZEDLOG_TEST;

    /**
     * The table <code>test.RAWLOG_TEST</code>.
     */
    public static final RawlogTest RAWLOG_TEST = com.treetory.test.mvc.model.test.tables.RawlogTest.RAWLOG_TEST;
}
