/*
 * This file is generated by jOOQ.
 */
package com.treetory.test.mvc.model.test;


import com.treetory.test.mvc.model.test.tables.NormalizedlogTest;
import com.treetory.test.mvc.model.test.tables.RawlogTest;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends SchemaImpl {

    private static final long serialVersionUID = -248956905;

    /**
     * The reference instance of <code>test</code>
     */
    public static final Test TEST = new Test();

    /**
     * The table <code>test.NORMALIZEDLOG_TEST</code>.
     */
    public final NormalizedlogTest NORMALIZEDLOG_TEST = com.treetory.test.mvc.model.test.tables.NormalizedlogTest.NORMALIZEDLOG_TEST;

    /**
     * The table <code>test.RAWLOG_TEST</code>.
     */
    public final RawlogTest RAWLOG_TEST = com.treetory.test.mvc.model.test.tables.RawlogTest.RAWLOG_TEST;

    /**
     * No further instances allowed
     */
    private Test() {
        super("test", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            NormalizedlogTest.NORMALIZEDLOG_TEST,
            RawlogTest.RAWLOG_TEST);
    }
}
